fail_fast: true
repos:
- repo: local
  hooks:
    - id: black
      name: black
      entry: poetry run black ./app
      language: system
      types: [file, python]
    - id: isort
      name: isort
      entry: poetry run isort ./app
      language: system
      types: [file, python]
